name: 'ci'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4.1.1'

      - name: 'Setup Python'
        uses: 'actions/setup-python@v5.0.0'
        with:
          python-version: '3.10.x'
          cache: 'pipenv'

      - name: 'Install Pipenv'
        run: 'pip install pipenv'

      - run: 'pipenv install --dev'

      - run: 'pipenv shell'

      - run: 'pipenv run lint-autopep8'
      - run: 'pipenv run lint-mypy'
      - run: 'pipenv run lint-editorconfig'
